### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by cmgmyr**
https://app.asana.com/0/1156667858696586/1156075392616963

This PR bumps up all of the dev dependencies to get rid of our security issues. I also had to reference the parser classes differently because the test suite was failing since it wanted absolute paths compared to a string.

### CODE REVIEW

**Comment by snags88** [comment]
Could you make sure that this gets released on NPM and propagated out to our repositories?

**Comment by cmgmyr** [comment]
Yup, I’ll look into that tomorrow. Do I need any special access to NPM? Haven’t published anything there yet

**Comment by snags88** [comment]
There's a shared login for NPM on 1Password:

https://www.notion.so/curology/Deploying-to-Production-ea4de3384590419ebede6798749f7933#cdd5e280d41044139165e357b6cc98d0

**Comment by snags88** [comment]
^those steps are for radiance so it's gonna be a little bit different for this repo.

**Pull request merged**
